// !!! This file is automatically generated by the build/prebuild.js (via npm run prebuild).
// !!! Please do not modify manually.

import { filterArray, filterArrayMulti, filterBoolean, filterMoney, filterTime } from './filters';
import HelloWorld from '../components/hello-world/hello-world';
import FileDownload from '../components/file-download/file-download';
import SwitchController from '../components/switch-controller/switch-controller';
import LinesEllipsis from '../components/lines-ellipsis/lines-ellipsis';
import Layout from '../components/layout/layout';
import EmptyLayout from '../components/layout/empty-layout/empty-layout';
import LayoutBreadcrumb from '../components/layout/layout-breadcrumb/layout-breadcrumb';
import LayoutSidebar from '../components/layout/layout-sidebar/layout-sidebar';
import { VueConstructor } from 'vue';
import { calcFinalOpts, XluckyOpts } from './options';

const components = [
  { name: 'XvHelloWorld', component: HelloWorld },
  { name: 'XvFileDownload', component: FileDownload },
  { name: 'XvSwitchController', component: SwitchController },
  { name: 'XvLinesEllipsis', component: LinesEllipsis },
  { name: 'XvLayout', component: Layout },
  { name: 'XvEmptyLayout', component: EmptyLayout },
  { name: 'XvLayoutBreadcrumb', component: LayoutBreadcrumb },
  { name: 'XvLayoutSidebar', component: LayoutSidebar },
];

function install(Vue: VueConstructor, opts?: XluckyOpts) {
  Vue.prototype.$xlucky = calcFinalOpts(opts);

  components.forEach((item) => {
    Vue.component(item.name, item.component);
  });

  Vue.filter('filterArray', filterArray);
  Vue.filter('filterArrayMulti', filterArrayMulti);
  Vue.filter('filterBoolean', filterBoolean);
  Vue.filter('filterMoney', filterMoney);
  Vue.filter('filterTime', filterTime);
}

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: process.env.PKG_VERSION,
  install,
  filterArray,
  filterArrayMulti,
  filterBoolean,
  filterMoney,
  filterTime,
  HelloWorld,
  FileDownload,
  SwitchController,
  LinesEllipsis,
  Layout,
  EmptyLayout,
  LayoutBreadcrumb,
  LayoutSidebar,
};
