// !!! This file is automatically generated by the build/prebuild.js.
// !!! Please do not modify manually.

import HelloWorld from '../components/hello-world/hello-world';

export default {
  version: '0.0.1',
  HelloWorld,
}
